<?php
$data = $block->getCurrencyRateData();
?>

<div>
    <img src="https://portal.vietcombank.com.vn/Resources/v3/img/logo.png" title="Ngân hàng Thương mại Cổ phần Ngoại thương Việt Nam - Vietcombank" style="
    width: 100px;">
    <div style="font-style:italic;">Dữ liệu được lấy từ Ngân hàng Vietcombank</div>
</div>
<p>Cập nhật lúc: <?php echo $data->DateTime ?> và chỉ mang tính chất tham khảo</p>
<table style="border-collapse: collapse; width: 100%;">
    <tbody>
        <style>
            tr:not(:first-child):hover {
                background-color: #888d8b;
            }
        </style>
        <tr>
            <td style="width: 40%; text-align: center; background-color: #000000; color: white;" colspan="2">Ngoại tệ</td>
            <td style="width: 40%; text-align: center; background-color: #000000; color: white;" colspan="2">Mua</td>
            <td style="width: 20%; text-align: center; background-color: #000000; color: white;" rowspan="2">Bán</td>
        </tr>
        <tr>
            <td style="text-align: center; background-color: #000000; color: white;">Tên ngoại tệ</td>
            <td style="text-align: center; background-color: #000000; color: white;">Mã ngoại tệ</td>
            <td style="text-align: center; background-color: #000000; color: white;">Tiền mặt</td>
            <td style="text-align: center; background-color: #000000; color: white;">Chuyển khoản</td>
        </tr>
        <?php
        foreach ($data->Exrate as $Exrates) {
        ?>
            <tr>
                <td><?php echo $Exrates['CurrencyName'] ?></td>
                <td><?php echo $Exrates['CurrencyCode'] ?></td>
                <td><?php echo $Exrates['Buy'] ?></td>
                <td><?php echo $Exrates['Transfer'] ?></td>
                <td><?php echo $Exrates['Sell'] ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>